version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeguard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - codeguard_tmp:/app/tmp
    env_file:
      - .env   # ✅ load environment variables (not pushed to GitHub)
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: codeguard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codeguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  python-runtime:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    container_name: codeguard-python
    volumes:
      - codeguard_tmp:/code
    command: tail -f /dev/null
    restart: unless-stopped

  c-runtime:
    build:
      context: ./backend
      dockerfile: Dockerfile.c
    container_name: codeguard-c
    volumes:
      - codeguard_tmp:/code
    command: tail -f /dev/null
    restart: unless-stopped

volumes:
  pgdata:
  codeguard_tmp:
