version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeguard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock   # backend can run docker CLI
      - ./backend/tmp:/app/tmp
    environment:
      - NODE_ENV=development
      - PORT=5000

      # 👇 Supabase connection settings
      - DB_USER=postgres
      - DB_PASSWORD=Codegaurd
      - DB_NAME=postgres             # Supabase default DB name is usually "postgres"
      - DB_HOST=db.slnvvhlbhzmmqbuwqokg.supabase.co
      - DB_PORT=5432
      - SESSION_SECRET=supersecret
    command: ["node", "src/server.js"]
    restart: unless-stopped

volumes:
  pgdata:
