services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeguard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock   # Allows backend container to use Docker CLI on host
      - ./backend/tmp:/app/tmp
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: ["node", "src/server.js"]
    restart: unless-stopped
