version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeguard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app                        # backend source code
      - /var/run/docker.sock:/var/run/docker.sock   # allow backend to run Docker
      - /tmp:/tmp                             # ✅ system tmp (shared with runner)
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=codeguard
      - DB_HOST=db
      - DB_PORT=5432
      - SESSION_SECRET=supersecret
    depends_on:
      - db
    command: ["node", "src/server.js"]
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: codeguard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codeguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # ✅ Custom Python runtime
  python-runtime:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    image: codeguard-python
    restart: unless-stopped

  # ✅ Custom C runtime
  c-runtime:
    build:
      context: ./backend
      dockerfile: Dockerfile.c
    image: codeguard-c
    restart: unless-stopped

volumes:
  pgdata:
