services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeguard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      # Docker socket mount is risky and may fail on Windows. Only keep if needed:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/tmp:/app/tmp
    environment:
      - NODE_ENV=development
    command: ["node", "src/server.js"]
